databases: 
  - name: alpha-auth-db 
    databaseName: alpha_auth 
    user: alpha_auth_user 
    plan: free 
 
services: 
  - type: web 
    name: alpha-auth-backend 
    runtime: docker 
    plan: free   # can upgrade if needed 
    branch: feature/student   # <-- correct branch 
    autoDeploy: true 
    dockerfilePath: ./Dockerfile 
    envVars: 
      - key: ENV 
        value: production 
      - key: DATABASE_URL 
        fromDatabase: 
          name: alpha-auth-db 
          property: connectionString 
      - key: JWT_SECRET_KEY 
        sync: false 
      - key: SENDGRID_API_KEY 
        sync: false 
      - key: ADMIN_EMAIL 
        sync: false 
      - key: ADMIN_PASS 
        sync: false
